export const auth = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAI",
  LOG_OUT: "LOG_OUT",
  LOAD_PROFILE: "LOAD_PROFILE",
};

export const video = {
  HOME_VIDEOS_REQUEST: "HOME_VIDEOS_REQUEST",
  HOME_VIDEOS_SUCCESS: "HOME_VIDEOS_SUCCESS",
  HOME_VIDEOS_FAIL: "HOME_VIDEOS_FAIL",
};

export const selectedVideo = {
  SELECTED_VIDEO_REQUEST: "SELECTED_VIDEO_REQUEST",
  SELECTED_VIDEO_SUCCESS: "SELECTED_VIDEO_SUCCESS",
  SELECTED_VIDEO_FAIL: "SELECTED_VIDEO_FAIL",
};

export const channel = {
  CHANNEL_DETAILS_REQUEST: "CHANNEL_DETAILS_REQUEST",
  CHANNEL_DETAILS_SUCCESS: "CHANNEL_DETAILS_SUCCESS",
  CHANNEL_DETAILS_FAIL: "CHANNEL_DETAILS_FAIL",
};

export const comment = {
  COMMENT_LIST_SUCCESS: "COMMENT_LIST_SUCCESS",
  COMMENT_LIST_FAIL: "COMMENT_LIST_FAIL",
  COMMENT_LIST_REQUEST: "COMMENT_LIST_REQUEST",
};

export const SET_SUBSCRIPTION_STATUS = "SET_SUBSCRIPTION_STATUS";

export const relatedVideo = {
  RELATED_VIDEO_REQUEST: "RELATED_VIDEO_REQUEST",
  RELATED_VIDEO_SUCCESS: "RELATED_VIDEO_SUCCESS",
  RELATED_VIDEO_FAIL: "RELATED_VIDEO_FAIL",
};

export const search = {
  SEARCHED_VIDEO_REQUEST: "SEARCHED_VIDEO_REQUEST",
  SEARCHED_VIDEO_SUCCESS: "SEARCHED_VIDEO_SUCCESS",
  SEARCHED_VIDEO_FAIL: "SEARCHED_VIDEO_FAIL",
};

export const subscription = {
  SUBSCRIPTIONS_CHANNEL_REQUEST: "SUBSCRIPTIONS_CHANNEL_REQUEST",
  SUBSCRIPTIONS_CHANNEL_SUCCESS: "SUBSCRIPTIONS_CHANNEL_SUCCESS",
  SUBSCRIPTIONS_CHANNEL_FAIL: "SUBSCRIPTIONS_CHANNEL_FAIL",
};

export const channelVideo = {
  CHANNEL_VIDEOS_REQUEST: "CHANNEL_VIDEOS_REQUEST",
  CHANNEL_VIDEOS_SUCCESS: "CHANNEL_VIDEOS_SUCCESS",
  CHANNEL_VIDEOS_FAIL: "CHANNEL_VIDEOS_FAIL",
};

export const createComment = {
  CREATE_COMMENT_FAIL: "CREATE_COMMENT_FAIL",
  CREATE_COMMENT_SUCCESS: "CREATE_COMMENT_SUCCESS",
};
